name: cd

on:
  push:
    branches:
      - 'main'

env:
  IMAGE: frontend
  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set env
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
      - name: Test
        run: echo $IMAGE_TAG
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_TAG }}
